name: automerge

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 14.x
          working-directory: ./ClientApp
      - run: npm ci
      - run: npm run build
  automerge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.10.2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
